import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {
  writeUpdateCache,
  writeClaudeSession,
  writeCodexSession,
  writeOpenClawSetup,
  runAgents,
  outputOf,
} from './sessions.test-fixture.js';

describe('agents sessions', () => {
  // 90s, not the default 30s: several real `agents` CLI boots, measured 6.5s
  // idle and 13.7s under 16 CPU-bound background processes (RUSH-2839).
  it('lists only sessions from the current directory by default and shows all with --all', () => {
    const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'agents-sessions-list-'));

    try {
      writeUpdateCache(tempHome);

      const phnxDir = path.join(tempHome, 'work', 'phnx-labs');
      const agentsCliDir = path.join(tempHome, 'work', 'agents-cli');
      const phnxSessionId = '11111111-1111-4111-8111-111111111111';
      const agentsCliSessionId = '22222222-2222-4222-8222-222222222222';

      writeClaudeSession(
        tempHome,
        'phnx-labs-test',
        phnxSessionId,
        phnxDir,
        'Inspect the phnx-labs session list',
        '2026-04-17T19:35:30.000Z'
      );
      writeClaudeSession(
        tempHome,
        'agents-cli-test',
        agentsCliSessionId,
        agentsCliDir,
        'Inspect the agents-cli session list',
        '2026-04-17T19:36:30.000Z'
      );

      const localResult = runAgents(['sessions'], phnxDir, tempHome);
      expect(localResult.status).toBe(0);

      const localOutput = outputOf(localResult);
      expect(localOutput).toContain(phnxSessionId.slice(0, 8));
      expect(localOutput).not.toContain(agentsCliSessionId.slice(0, 8));

      const allResult = runAgents(['sessions', '--all'], phnxDir, tempHome);
      expect(allResult.status).toBe(0);

      const allOutput = outputOf(allResult);
      expect(allOutput).toContain(phnxSessionId.slice(0, 8));
      expect(allOutput).toContain(agentsCliSessionId.slice(0, 8));
    } finally {
      fs.rmSync(tempHome, { recursive: true, force: true });
    }
  }, 90_000);

  it('shows message and token counts while skipping Claude local-command preambles in the topic', () => {
    const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'agents-sessions-stats-'));

    try {
      writeUpdateCache(tempHome);

      const repoDir = path.join(tempHome, 'work', 'agents-cli');
      const projectKey = 'agents-cli-test';
      const sessionId = '77777777-7777-4777-8777-777777777777';

      fs.mkdirSync(repoDir, { recursive: true });
      fs.mkdirSync(path.join(tempHome, '.claude', 'projects', projectKey), { recursive: true });
      fs.writeFileSync(
        path.join(tempHome, '.claude', 'projects', projectKey, `${sessionId}.jsonl`),
        [
          JSON.stringify({
            type: 'user',
            timestamp: '2026-04-17T19:00:00.000Z',
            cwd: repoDir,
            sessionId,
            version: '2.1.110',
            gitBranch: 'main',
            isMeta: true,
            message: {
              role: 'user',
              content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
            },
          }),
          JSON.stringify({
            type: 'user',
            timestamp: '2026-04-17T19:00:01.000Z',
            cwd: repoDir,
            sessionId,
            version: '2.1.110',
            gitBranch: 'main',
            message: { role: 'user', content: '<bash-input>pwd</bash-input>' },
          }),
          JSON.stringify({
            type: 'user',
            timestamp: '2026-04-17T19:00:02.000Z',
            cwd: repoDir,
            sessionId,
            version: '2.1.110',
            gitBranch: 'main',
            message: { role: 'user', content: 'Inspect session stats' },
          }),
          JSON.stringify({
            type: 'assistant',
            timestamp: '2026-04-17T19:00:03.000Z',
            cwd: repoDir,
            sessionId,
            version: '2.1.110',
            gitBranch: 'main',
            message: {
              id: 'msg-stats',
              role: 'assistant',
              content: [{ type: 'text', text: 'Looking now.' }],
              usage: {
                input_tokens: 10,
                output_tokens: 5,
                cache_read_input_tokens: 20,
                cache_creation_input_tokens: 0,
              },
            },
          }),
          JSON.stringify({
            type: 'assistant',
            timestamp: '2026-04-17T19:00:04.000Z',
            cwd: repoDir,
            sessionId,
            version: '2.1.110',
            gitBranch: 'main',
            message: {
              id: 'msg-stats',
              role: 'assistant',
              content: [{ type: 'tool_use', id: 'tool-1', name: 'Read', input: { file_path: '/tmp/example' } }],
              usage: {
                input_tokens: 10,
                output_tokens: 5,
                cache_read_input_tokens: 20,
                cache_creation_input_tokens: 0,
              },
            },
          }),
        ].join('\n') + '\n',
        'utf-8'
      );

      const result = runAgents(['sessions'], repoDir, tempHome);
      expect(result.status).toBe(0);

      const output = outputOf(result);
      // Core intent of this test: topic rendering skips the Claude
      // local-command preamble ("Caveat: ...") and shows the real prompt.
      // The Msgs/Tokens column assertion was dropped when the session table
      // was simplified to ID / agent / project / topic / when.
      const row = output.split('\n').find(line => line.includes(sessionId.slice(0, 8))) || '';
      expect(row).toContain('Inspect session stats');
      expect(row).not.toContain('Caveat:');
    } finally {
      fs.rmSync(tempHome, { recursive: true, force: true });
    }
  });

  it('finds matching projects outside the current directory when --project is provided', () => {
    const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'agents-sessions-project-'));

    try {
      writeUpdateCache(tempHome);

      const workspaceDir = path.join(tempHome, 'work');
      const phnxDir = path.join(workspaceDir, 'phnx-labs');
      const agentsCliDir = path.join(workspaceDir, 'agents-cli');
      const phnxSessionId = '55555555-5555-4555-8555-555555555555';
      const agentsCliSessionId = '66666666-6666-4666-8666-666666666666';

      fs.mkdirSync(workspaceDir, { recursive: true });

      writeClaudeSession(
        tempHome,
        'phnx-labs-test',
        phnxSessionId,
        phnxDir,
        'Inspect the phnx-labs session list',
        '2026-04-17T19:35:30.000Z'
      );
      writeClaudeSession(
        tempHome,
        'agents-cli-test',
        agentsCliSessionId,
        agentsCliDir,
        'Inspect the agents-cli session list',
        '2026-04-17T19:36:30.000Z'
      );

      const result = runAgents(['sessions', '--project', 'agents-cli'], workspaceDir, tempHome);
      expect(result.status).toBe(0);

      const output = outputOf(result);
      expect(output).toContain(agentsCliSessionId.slice(0, 8));
      expect(output).not.toContain(phnxSessionId.slice(0, 8));
      expect(output).not.toContain(`No sessions found for ${workspaceDir}`);
    } finally {
      fs.rmSync(tempHome, { recursive: true, force: true });
    }
  });

  it('shows the first human Codex prompt instead of injected session scaffolding', () => {
    const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'agents-sessions-codex-topic-'));

    try {
      writeUpdateCache(tempHome);

      const projectDir = path.join(tempHome, 'work', 'agents-cli');
      const sessionId = '99999999-9999-4999-8999-999999999999';
      const prompt = 'Search across sessions by prompt text';

      writeCodexSession(
        tempHome,
        sessionId,
        projectDir,
        prompt,
        '2026-04-17T19:40:30.000Z'
      );

      const result = runAgents(['sessions', '--all'], projectDir, tempHome);
      expect(result.status).toBe(0);

      const output = outputOf(result);
      expect(output).toContain(sessionId.slice(0, 8));
      expect(output).toContain(prompt);
      expect(output).not.toContain('Collaboration Mode: Default');
      expect(output).not.toContain('# AGENTS.md instructions');
    } finally {
      fs.rmSync(tempHome, { recursive: true, force: true });
    }
  });

  it('lists Codex sessions when filtered by --agent', () => {
    const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'agents-sessions-codex-version-'));

    try {
      writeUpdateCache(tempHome);

      const projectDir = path.join(tempHome, 'work', 'agents-cli');
      writeCodexSession(
        tempHome,
        'abababab-abab-4bab-8bab-abababababab',
        projectDir,
        'Show codex versions in the session list',
        '2026-04-17T19:42:30.000Z'
      );

      const result = runAgents(['sessions', '--agent', 'codex', '--all'], projectDir, tempHome);
      expect(result.status).toBe(0);

      const output = outputOf(result);
      // Table simplification dropped the "codex@<version>" suffix from the
      // agent column; still verify the codex session is discovered & listed.
      expect(output).toContain('codex');
      expect(output).toContain('Show codex versions in the session list');
      expect(output).toContain('abababab');
    } finally {
      fs.rmSync(tempHome, { recursive: true, force: true });
    }
  });

  it('combines --agent and --version into one structured session filter', () => {
    const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'agents-sessions-agent-version-flags-'));
    try {
      writeUpdateCache(tempHome);
      const projectDir = path.join(tempHome, 'work', 'agents-cli');
      writeCodexSession(tempHome, 'acacacac-acac-4cac-8cac-acacacacacac', projectDir,
        'Filter this exact Codex version', '2026-04-17T19:43:30.000Z');

      const match = runAgents(
        ['sessions', '--agent', 'codex', '--version', '0.113.0', '--all', '--no-interactive'],
        projectDir, tempHome,
      );
      expect(match.status, match.stderr).toBe(0);
      expect(outputOf(match)).toContain('Filter this exact Codex version');

      const miss = runAgents(
        ['sessions', '--agent', 'codex', '--version', '9.9.9', '--all', '--no-interactive'],
        projectDir, tempHome,
      );
      expect(miss.status, miss.stderr).toBe(0);
      expect(outputOf(miss)).not.toContain('Filter this exact Codex version');
    } finally {
      fs.rmSync(tempHome, { recursive: true, force: true });
    }
  });

  it('rejects --version without an agent instead of silently ignoring it', () => {
    const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'agents-sessions-version-without-agent-'));
    try {
      writeUpdateCache(tempHome);
      const result = runAgents(['sessions', '--version', '2.1.181', '--no-interactive'], tempHome, tempHome);
      expect(result.status).toBe(1);
      expect(result.stderr).toContain('--version requires --agent');
    } finally {
      fs.rmSync(tempHome, { recursive: true, force: true });
    }
  });

  it.each([
    [['sessions', '--version']],
    [['sessions', '--agent', 'claude', '--version', '--no-interactive']],
  ])('rejects a sessions --version flag with no value: %j', (args) => {
    const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'agents-sessions-version-without-value-'));
    try {
      writeUpdateCache(tempHome);
      const result = runAgents(args, tempHome, tempHome);
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("option '--version <version>' argument missing");
    } finally {
      fs.rmSync(tempHome, { recursive: true, force: true });
    }
  });

  // The fixture's openclaw binary is a `#!/bin/sh` script and the assertions
  // depend on its stdout (channels status / cron list) — shebang scripts don't
  // execute on Windows, so there's no synthetic-session data to discover there.
  it.skipIf(process.platform === 'win32')('shows OpenClaw synthetic sessions from the configured workspace without --all', () => {
    const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'agents-sessions-openclaw-cwd-'));

    try {
      writeUpdateCache(tempHome);
      const openClawWorkspace = writeOpenClawSetup(tempHome);

      const result = runAgents(['sessions', '--agent', 'openclaw'], openClawWorkspace, tempHome);
      expect(result.status).toBe(0);

      const output = outputOf(result);
      // The "openclaw@<version>" suffix was dropped with the table
      // simplification; the workspace discovery (Sergey / session id) is the
      // actual behavior this test guards.
      expect(output).toContain('Sergey');
      expect(output).toContain('12345678');
      expect(output).not.toContain('No sessions found');
    } finally {
      fs.rmSync(tempHome, { recursive: true, force: true });
    }
  });
});
