FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    git \
    libsecret-tools \
    dbus-x11 \
    gnome-keyring \
    && rm -rf /var/lib/cache/apt

RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"

ENV DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/0/bus"

WORKDIR /app/cli
COPY . /app

RUN bun install
RUN bun run build

CMD ["bash", "-c", "\
    eval $(dbus-launch --sh-syntax) && \
    echo 'test' | gnome-keyring-daemon --unlock --components=secrets && \
    bun test src/lib/secrets \
"]
